//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleRND.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\v11.0;Initial Catalog=\"3E636A05BB0B7ADA74DDF8F55BA6A48A_NET" +
            " 4.5 WEB FORMS AND VISUAL STUDIO 2013 - WINGTIP TOYS\\C#\\WINGTIPTOYS\\APP_DATA\\WIN" +
            "GTIPTOYS.MDF\";Integrated Security=True;Connect Timeout=30")]
        public string _3E636A05BB0B7ADA74DDF8F55BA6A48A_NET_4_5_WEB_FORMS_AND_VISUAL_STUDIO_2013___WINGTIP_TOYS_C__WINGTIPTOYS_APP_DATA_WINGTI {
            get {
                return ((string)(this["_3E636A05BB0B7ADA74DDF8F55BA6A48A_NET_4_5_WEB_FORMS_AND_VISUAL_STUDIO_2013___WING" +
                    "TIP_TOYS_C__WINGTIPTOYS_APP_DATA_WINGTI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\v11.0;Initial Catalog=BDConsoleRND;Integrated Security=True" +
            ";Connect Timeout=30")]
        public string BDConsoleRNDConnectionString {
            get {
                return ((string)(this["BDConsoleRNDConnectionString"]));
            }
        }
    }
}
